### ISSUE TITLE
Compact approach to output

### ISSUE THREAD

**Issue by XinYenFon** [hyena/blood-money#4]
Hello,

I saw your project on wowhead today and followed it bit, as you noted you are not well with CSS, I wanted to step forward and help you on the html output. You can look at my past from my profile. I`m still learning the RUST at this stage (very basics of it compile - run on web server etc...).

What I`m offering (suggesting) is to make more compact view so it wont take ages to scroll down. Also I can make it responsive so it will be mobile ready.

This is my very first draft (direct HTML edit on your page so bars are just went all the way down due to flex view).
![screenshot-rodent io-2017-11-12-03-29-30](https://user-images.githubusercontent.com/1669995/32694785-5139676c-c75a-11e7-9dc2-24535badae97.png)

Let me know if this version is fine enough, thanks for the handy web-app.

**Comment by hyena** [comment]
I think a two column (responsive) view is definitely the way to go. The main stickler is the 'grid' format and making sure the bars are aligned elegantly. I think that the bars are an important visualization to quickly impart visually the relative values of the options in a way that numbers alone don't convey, so they should be a part of any solution. But the way it's done now is a bit of a kludge:

As you've probably seen from looking at the code, each section is divided into two columns: The left contains the icons and the names, the right contains the values and the bars. I did it this way because it made it easy to make the left column a consistent width for all items. To make sure the bars line up with them is a bit of a hack: I made sure the bars were the same height as the icons and I inserted lines of whitespace for things like the mats or crafting/trading notes so there's the same height for all the text.

Unfortunately out of the box flexbox doesn't lend itself immediately to this kind of grid approach, although I've seen some approaches that might work.

The easiest thing might be to enclose each section (i.e. Blood and Sargerite) in its own div and arrange those in a flex container that tries to place them in a row.
